name: Flutter CI

on: push
jobs: 
  
 buildFlutter: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    - run: dart --version
   # - run: dart pub outdated --mode=null-safety
   #- run: dart pub upgrade --null-safety 
    - run: dart pub get
   # - run: dart analyze 
  #  - run: dart migrate 
    #- name: Get flutter dependencies.
    #- run: flutter --no-sound-null-safety
    - run: flutter pub get
    

 
    #- name: Run tests for our flutter project once we add unit tests.
    #- run: flutter test
    
      #- name: Build apk.
  #  - run: flutter build apk
    # found syntax errors in the sourcecode
   #   working-directory: ./
    #- run: flutter build appbundle


 buildUnitTest:
     runs-on: ubuntu-latest
#runs unit tests located in the project.  (- name: Assemble app debug APK)  
     steps:
       # - name: Run Unit tests
        #  run: bash ./gradlew test --stacktrace
         # env:
          #  WAP_API_KEY: ${{ secrets.WAP_API_KEY }}

        - name: Upload Android Test APK
          uses: actions/upload-artifact@v1
          with:
            name: app-debug-androidTest
            path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk  
            
 buildFirebase:
    runs-on: ubuntu-latest
   
        #needs: apk  #Dapat na build na daan tong APK above but naa may error due to ./gradlew nga file
        
    steps:
      - uses: actions/checkout@v1
      - name: Download app APK  #download all the artifacts we generated in the previous step
        uses: actions/download-artifact@v1
        with:
          name: app-debug
      - name: Download Android test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

     
  

