name: Flutter CI
env:
  FLUTTER_VERSION: "stable"
defaults:
  run:
    working-directory: client
    
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '12.X'
        distribution: 'adopt'
#set up flutter
  buildFlutter:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
       - name: Installing Flutter
         uses: britannio/action-install-flutter@v1.0
         with:
          version: $FLUTTER_VERSION
          run: flutter doctor --android-licenses
       #- run: echo $PATH
          #run: where flutter 
       
       #- name: Installing dependencies
        # run: flutter pub get
      # - name: Running tests
       #  run: flutter test --no-pub
  buildAndroid:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleDebug"
